name: wallet
description: A new Flutter package project.
version: 0.0.1
homepage: leonardobido.me
publish_to: "none"

environment:
  sdk: ">=2.19.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  base_style_sheet:
    path: ../base_style_sheet

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  