name: base_auth
description: A new Flutter package project.
version: 0.0.1
homepage: leonardobido.me
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  base_style_sheet:
    path: ../base_style_sheet
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^1.0.0
  mockito: ^5.2.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
