library core;

export 'package:dartz/dartz.dart' show Either, Right, Left, Unit, unit;
export 'package:flutter_modular/flutter_modular.dart';
export 'package:dio/dio.dart';
export 'package:flutter_triple/flutter_triple.dart';
export 'package:google_fonts/google_fonts.dart';
export 'package:core/src/utils/router_observer.dart';
export 'package:core/src/constants/mapping_colors.dart';
export 'package:core/src/utils/load_mock.dart';
export 'package:core/src/infra/drivers/http_driver.dart';
export 'package:core/src/domain/services/connectivity_service.dart';
export 'package:core/src/data/drivers/connectivity_driver.dart';
export 'package:core/src/infra/drivers/connectivity_driver.dart';
export 'package:core/src/infra/services/connectivity_service.dart';
export 'package:connectivity_plus/connectivity_plus.dart';
export 'package:core/src/data/drivers/local_storage_driver.dart';
export 'package:core/src/data/drivers/dio/dio_client.dart';
export 'package:core/src/presentation/shared/pages/not_found/not_found_page.dart';
export 'package:core/src/domain/entities/logged_user_entity.dart';
export 'package:core/src/infra/models/logged_user_model.dart';
export 'package:core/src/data/drivers/dio/default_interceptors.dart';
export 'package:flutter_svg/svg.dart';
export 'package:core/src/utils/formats.dart';
export 'package:core/src/infra/drivers/preferences_storage_driver.dart';
export 'package:core/src/data/drivers/preferences_storage_driver.dart';
export 'package:shared_preferences/shared_preferences.dart';
